version: build-{build}
clone_folder: c:\projects\janet
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
    - build_win
    - build_win test
    - choco install nsis -y -pre
    - build_win dist
    
build: off

only_commits:
  files:
    - appveyor.yml
    - src/

artifacts:
    - path: janet-installer.exe
      name: janet-v1.2.0-windows-installer.exe
      type: File

deploy:
  description: 'The Janet Programming Language.'
  provider: GitHub
  auth_token:
    secure: lwEXy09qhj2jSH9s1C/KvCkAUqJSma8phFR+0kbsfUc3rVxpNK5uD3z9Md0SjYRx
  artifact: janet-windows
  draft: true
  on:
      APPVEYOR_REPO_TAG: true
