version: build-{build}
clone_folder: c:\projects\janet
image:
- Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"

install:
    - choco install nsis -y -pre
    # Replace makensis.exe and files with special long string build. This should
    # prevent issues when setting PATH during installation.
    - 7z e "tools\nsis-3.04-strlen_8192.zip" -o"C:\Program Files (x86)\NSIS\" -y
    - build_win all
    - refreshenv
    # We need to reload vcvars after refreshing
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
    - build_win test-install
build: off

only_commits:
  files:
    - appveyor.yml
    - src/

artifacts:
    - path: janet-v1.2.0-windows-installer.exe
      name: janet-v1.2.0-windows-installer.exe
      type: File

deploy:
  description: 'The Janet Programming Language.'
  provider: GitHub
  auth_token:
    secure: lwEXy09qhj2jSH9s1C/KvCkAUqJSma8phFR+0kbsfUc3rVxpNK5uD3z9Md0SjYRx
  artifact: janet-windows
  draft: true
  on:
      APPVEYOR_REPO_TAG: true
