version: build-{build}
branches:
  only:
  - master
  - stable
clone_folder: c:\projects\janet
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
    - build_win
    - build_win test
    
build: off

only_commits:
  files:
    - appveyor.yml
    - src/

artifacts:
    - path: janet.exe
      name: janet.exe
      type: File
    - path: janet.def
      name: janet.def
      type: File
    - path: janet.lib
      name: janet.lib
      type: File
